org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = io.github.urntt
mod_id = litematica-creator
mod_name = Litematica Creator
author = urntt
mod_file_name = litematica-creator-fabric

mod_version = 0.1.0-dev

malilib_version = 0.29.2-sakura.4
litematica_version = 0.28.2-sakura.1

minecraft_version_out = 26.2
minecraft_version = 26.2

fabric_loader_version = 0.19.3
fabric_api_version = 0.153.0+26.2
mod_menu_version = 20.0.0-beta.3
