pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		gradlePluginPortal()
	}
}

rootProject.name = 'litematica-creator-26.2'

includeBuild('../litematica-26.2') {
	dependencySubstitution {
		substitute module('fi.dy.masa.litematica:litematica-fabric-26.2') using project(':')
		substitute module('fi.dy.masa:litematica-fabric-26.2') using project(':')
	}
}
